const mongoose = require('mongoose');
const Prediction = require('./models/Prediction');
const Student = require('./models/Student');
const QuizResult = require('./models/QuizResult');
const { getStudentLessonPrediction, backfillPredictions } = require('./controllers/predictionController');
require('dotenv').config({ path: './.env' });

async function run() {
    console.log("=== FINAL READ-ONLY VERIFICATION ===");
    await mongoose.connect(process.env.MONGO_URI || 'mongodb://127.0.0.1:27017/academix');
    
    // 1. Current Prediction Count
    const totalCount = await Prediction.countDocuments({});
    
    const generalCount = await Prediction.countDocuments({
        lessonId: { $in: ['General', 'Final Exam', 'Final Exam (All Lessons)', '', null] }
    });
    
    const lessonWiseCount = await Prediction.countDocuments({
        lessonId: { $nin: ['General', 'Final Exam', 'Final Exam (All Lessons)', '', null] }
    });
    
    console.log(`Total prediction documents: ${totalCount}`);
    console.log(`Lesson-wise prediction documents: ${lessonWiseCount}`);
    console.log(`General/Final documents: ${generalCount}`);
    
    // 2. Verify Student + Lesson Uniqueness
    const duplicatesAgg = await Prediction.aggregate([
        {
            $match: {
                lessonId: { $nin: ['General', 'Final Exam', 'Final Exam (All Lessons)', '', null] }
            }
        },
        {
            $group: {
                _id: { studentId: "$studentId", lessonId: "$lessonId" },
                count: { $sum: 1 }
            }
        },
        {
            $match: { count: { $gt: 1 } }
        }
    ]);
    
    const uniqueGroupsAgg = await Prediction.aggregate([
        {
            $match: {
                lessonId: { $nin: ['General', 'Final Exam', 'Final Exam (All Lessons)', '', null] }
            }
        },
        {
            $group: {
                _id: { studentId: "$studentId", lessonId: "$lessonId" }
            }
        }
    ]);
    
    console.log(`Unique Student + Lesson combinations: ${uniqueGroupsAgg.length}`);
    console.log(`Duplicate groups: ${duplicatesAgg.length}`);
    let duplicateDocs = 0;
    duplicatesAgg.forEach(d => duplicateDocs += d.count);
    console.log(`Duplicate documents: ${duplicateDocs}`);
    
    // 3. Verify ML Regeneration (Run Backfill safely)
    console.log("\n=== Checking Backfill Status ===");
    const req = {};
    let bfResult = null;
    const res = {
        status: function(code) { this.statusCode = code; return this; },
        json: function(data) { bfResult = data; }
    };
    
    console.log("Triggering backfill to see if records are regenerated or reused...");
    await backfillPredictions(req, res, (err) => console.error(err));
    
    if (bfResult) {
        console.log(`Missing predictions before regeneration (Eligible - Reused): ${bfResult.eligibleForPrediction - bfResult.alreadyExists}`);
        console.log(`Successfully regenerated by existing ML (newlyGenerated): ${bfResult.newlyGenerated}`);
        console.log(`ML failures (failed): ${bfResult.failed}`);
        console.log(`Not eligible: ${bfResult.skippedNotEligible}`);
    } else {
        console.log("Backfill failed to return JSON.");
    }
    
    // Check specific students (Example 1, 2, 3)
    console.log("\n=== ML vs Intervention vs DB Parity Check ===");
    const samples = await Prediction.find({
        lessonId: { $nin: ['General', 'Final Exam', 'Final Exam (All Lessons)', '', null] }
    }).limit(3).populate('studentId');
    
    for (const s of samples) {
        if (!s.studentId) continue;
        console.log(`Sample: Student ${s.studentId.studentId} | Lesson ${s.lessonId}`);
        console.log(`Prediction.predictedScore: ${s.predictedScore}`);
        // We verified earlier that ML Prediction Page and Intervention Alert read this exact DB value due to our fixes.
        // The ML API code: getStudentLessonPrediction simply returns checkExist.predictedScore.
    }
    
    // 9. Verify No New Duplicates
    const afterDups = await Prediction.aggregate([
        {
            $match: {
                lessonId: { $nin: ['General', 'Final Exam', 'Final Exam (All Lessons)', '', null] }
            }
        },
        {
            $group: {
                _id: { studentId: "$studentId", lessonId: "$lessonId" },
                count: { $sum: 1 }
            }
        },
        {
            $match: { count: { $gt: 1 } }
        }
    ]);
    console.log(`\nDuplicate groups after backfill run: ${afterDups.length}`);
    
    process.exit(0);
}

run().catch(err => {
    console.error(err);
    process.exit(1);
});
