# -*- coding: utf-8 -*-
"""Raggg.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ofYRzqetnmPdtjP7ipctAkRsYIhhO-3P
"""

# Check Python version
!python --version

# Upgrade pip
!pip install --upgrade pip

!pip install -q \
langchain \
langchain-community \
langchain-google-genai \
langchain-huggingface \
langchain-text-splitters \
langchain-chroma \
chromadb \
sentence-transformers \
PyPDF2 \
python-dotenv \
google-generativeai

import os

from PyPDF2 import PdfReader

from langchain_text_splitters import RecursiveCharacterTextSplitter

from langchain_huggingface import HuggingFaceEmbeddings

from langchain_chroma import Chroma

from langchain_google_genai import ChatGoogleGenerativeAI

import os

os.environ["GOOGLE_API_KEY"] = "AQ.Ab8RN6LdnE_AgMdvTwMxi9jorGJcck3V9aGd3ABNtSZcFtdaIw"

llm = ChatGoogleGenerativeAI(
    model="gemini-2.5-flash",
    temperature=0.3
)

response = llm.invoke("Explain what ICT is in two sentences.")

print(response.content)

embedding = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

print("Embedding model loaded successfully!")

print("Gemini Model:", llm)
print("Embedding Model:", embedding)

import os
from PyPDF2 import PdfReader

def extract_text(pdf_path):
    reader = PdfReader(pdf_path)

    text = ""

    for page in reader.pages:
        page_text = page.extract_text()

        if page_text:
            text += page_text + "\n"

    return text

from google.colab import drive
drive.mount('/content/drive')
pdf_files = [
    {
        "path": "/content/drive/MyDrive/Teacher_Resources/Resources/Grade 10 ICT - Lesson 01 - Module 1.pdf",
        "module": "1.1",
        "title": "Introduction to ICT"
    },

    {
        "path": "/content/drive/MyDrive/Teacher_Resources/Resources/Grade 10 ICT - Lesson 01 - Module 2.pdf",
        "module": "1.2",
        "title": "Applications of ICT in Daily Life"
    },

    {
        "path": "/content/drive/MyDrive/Teacher_Resources/Resources/Grade 10 ICT - Lesson 01 - Module 3.pdf",
        "module": "1.3",
        "title": "Benefits and Challenges of ICT"
    }
]

documents = []

for pdf in pdf_files:

    text = extract_text(pdf["path"])

    documents.append({
        "text": text,
        "module": pdf["module"],
        "title": pdf["title"],
        "source": pdf["path"]
    })

print("Documents Loaded :", len(documents))

from langchain_text_splitters import RecursiveCharacterTextSplitter

splitter = RecursiveCharacterTextSplitter(

    chunk_size=800,

    chunk_overlap=150,

    separators=["\n\n","\n",". "," ",""]

)

texts = []

metadatas = []

for doc in documents:

    chunks = splitter.split_text(doc["text"])

    for chunk in chunks:

        texts.append(chunk)

        metadatas.append({

            "module": doc["module"],

            "title": doc["title"],

            "source": doc["source"]

        })

print("Total Chunks :", len(texts))

print(texts[0])

print(metadatas[0])

from langchain_huggingface import HuggingFaceEmbeddings

embedding_model = HuggingFaceEmbeddings(

    model_name="sentence-transformers/all-MiniLM-L6-v2"

)

embeddings = embedding_model.embed_documents(texts)

print("Number of embeddings :", len(embeddings))

print("Dimension :", len(embeddings[0]))

print(embeddings[0][:10])

from langchain_chroma import Chroma

vectordb = Chroma.from_texts(
    texts=texts,
    embedding=embedding_model,
    metadatas=metadatas,
    persist_directory="./ICT_RAG_DB"
)

print("ChromaDB created successfully!")

data = vectordb.get()

print("Total Documents :", len(data["documents"]))

for i in range(3):

    print("="*80)

    print("Metadata")

    print(data["metadatas"][i])

    print()

    print("Chunk")

    print(data["documents"][i])

    print()

retriever = vectordb.as_retriever(

    search_type="similarity",

    search_kwargs={
        "k":5
    }

)

query = "What is Telemedicine?"

docs = retriever.invoke(query)

for i, doc in enumerate(docs):

    print("="*80)

    print("Result", i+1)

    print()

    print(doc.metadata)

    print()

    print(doc.page_content)

docs = vectordb.similarity_search(

    query="Computer Generations",

    k=5,

    filter={
        "module":"1.3"
    }

)

for doc in docs:

    print(doc.metadata)

    print(doc.page_content)

    print()

def retrieve_context(question, module=None, k=5):

    if module:

        docs = vectordb.similarity_search(

            question,

            k=k,

            filter={"module":module}

        )

    else:

        docs = vectordb.similarity_search(

            question,

            k=k

        )

    context = "\n\n".join([doc.page_content for doc in docs])

    return context

def build_rag_prompt(question, score, module):

    context = retrieve_context(question, module)

    prompt = f"""
You are an expert Grade 10 ICT teacher.

Student Performance

Module : {module}

Score : {score}%

Learning Material

{context}

Instructions

Generate a personalized study note.

If score is above 75%

- Give only a short revision note.
- Mention important facts only.

If score is between 50% and 75%

- Give a medium-length explanation.
- Explain key concepts.
- Include simple examples.

If score is below 50%

- Give a detailed explanation.
- Explain every important concept.
- Highlight common mistakes.
- Give examination tips.

Use only the learning material provided.

Do not invent new information.

Question

{question}
"""

    return prompt

prompt = build_rag_prompt(

    question="Explain the benefits and challenges of ICT.",

    score=20,

    module="1.3"

)

print(prompt)

from langchain_google_genai import ChatGoogleGenerativeAI

llm = ChatGoogleGenerativeAI(
    model="gemini-2.5-flash",
    temperature=0.3,
    google_api_key=os.environ["GOOGLE_API_KEY"]
)

student_performance = {
    "1.1": 80,
    "1.2": 60,
    "1.3": 20
}

def retrieve_module_context(module):

    docs = vectordb.similarity_search(
        query="important concepts",
        filter={"module": module},
        k=8
    )

    return "\n\n".join([doc.page_content for doc in docs])

def build_prompt(module, score):

    context = retrieve_module_context(module)

    prompt = f"""
You are an experienced Grade 10 ICT teacher.

A student completed a quiz.

Module : {module}

Quiz Score : {score}%

Below is the official learning material.

========================

{context}

========================

Your task is to create a PERSONALIZED STUDY PLAN.

The study plan MUST contain exactly these sections.

--------------------------------------------------

1. Performance Analysis

Explain the student's performance.

Mention whether this module is

• Strong

• Average

• Weak

--------------------------------------------------

2. Personalized Study Note

Generate a study note ONLY using the retrieved content.

Do NOT add external information.

If score >75%

Generate a concise revision note.

If score between 50 and 75

Generate a medium explanation.

If score below 50

Generate a detailed explanation.

--------------------------------------------------

3. Topics to Focus

List the most important topics.

--------------------------------------------------

4. Study Time Recommendation

Recommend study duration.

Example

30 Minutes

1 Hour

2 Hours

3 Hours

depending on performance.

--------------------------------------------------

5. Practice Questions

Generate practice questions according to score.

Score above 75

5 questions

Score 50-75

10 questions

Score below 50

15 questions

Questions should include

• Multiple Choice

• Short Answer

• Structured Questions

--------------------------------------------------

6. Motivation

End with a short motivational message.

Only use the retrieved learning material.

"""
    return prompt

module = "1.3"

score = 20

prompt = build_prompt(module, score)

response = llm.invoke(prompt)

print(response.content)

# Install required packages
!pip install -q fastapi uvicorn pyngrok nest-asyncio pydantic

# Imports
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from pyngrok import ngrok
import nest_asyncio
import uvicorn
import threading
import time

# ----------------------------------------
# FastAPI App
# ----------------------------------------

app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ----------------------------------------
# Request Model
# ----------------------------------------

class StudyPlanRequest(BaseModel):
    module: str
    score: int

# ----------------------------------------
# API Endpoint
# ----------------------------------------

@app.post("/generate_plan")
async def generate_plan_endpoint(req: StudyPlanRequest):
    try:
        # build_prompt() and llm should already exist
        prompt = build_prompt(req.module, req.score)

        response = llm.invoke(prompt)

        return {
            "success": True,
            "plan": response.content
        }

    except Exception as e:
        return {
            "success": False,
            "error": str(e)
        }

# ----------------------------------------
# Start FastAPI Server
# ----------------------------------------

nest_asyncio.apply()

def run():
    uvicorn.run(
        app,
        host="0.0.0.0",
        port=8000,
        log_level="info"
    )

server_thread = threading.Thread(target=run, daemon=True)
server_thread.start()

# Wait until server starts
time.sleep(3)

# ----------------------------------------
# Start ngrok
# ----------------------------------------

# Replace with your own ngrok auth token
ngrok.set_auth_token("3FrGzHC02Yd7tEJLloPgIaA9Who_gHecUftoxjLd8uURPmch")

# Close previous tunnels if any
ngrok.kill()

public_url = ngrok.connect(8000)

print("=" * 60)
print("🚀 YOUR RAG API IS LIVE")
print("=" * 60)
print(f"URL: {public_url.public_url}")
print("=" * 60)
print("POST Endpoint:")
print(f"{public_url.public_url}/generate_plan")
print("=" * 60)