/**
 * Utility to reliably parse Study Plan markdown generated by the RAG service.
 * Supports various LLM output formats, heading styles, and extracts structured data
 * for interactive UI components (Mistake Cards, Checklists, Glossaries, Schedules).
 */

export function extractScore(markdown) {
  if (!markdown) return null;

  const patterns = [
    /Overall\s+Score:\s*([\d.]+)/i,
    /overall\s+score\s+of\s*([\d.]+)/i,
    /score\s+of\s*([\d.]+)/i,
    /Your\s+score:\s*([\d.]+)/i,
    /achieved\s+an?\s+.*?\s+score\s+of\s*([\d.]+)/i,
    /(\d{1,3}(?:\.\d+)?)\s*%\s*(?:overall|indicates|tells|score)/i,
    /score:\s*(\d{1,3}(?:\.\d+)?)/i
  ];

  for (const regex of patterns) {
    const match = markdown.match(regex);
    if (match && match[1]) {
      const val = parseFloat(match[1]);
      if (!isNaN(val) && val >= 0 && val <= 100) {
        return Math.round(val * 10) / 10;
      }
    }
  }

  return null;
}

export function extractSections(markdown) {
  if (!markdown) return {};

  const lines = markdown.split('\n');
  const sections = {};
  let currentHeader = 'intro';
  let currentContent = [];

  const isHeading = (line) => {
    const trimmed = line.trim();
    if (trimmed.startsWith('#')) return true;
    if (/^\d+\.\s+[A-Z\s]{4,}/.test(trimmed)) return true;
    if (/^[A-Z\s]{5,}:?$/.test(trimmed) && trimmed.length < 60) return true;
    return false;
  };

  const normalizeHeader = (raw) => {
    return raw
      .replace(/^[#\d.\s\-*]+/, '')
      .replace(/\(.*?\)/g, '')
      .trim()
      .toUpperCase();
  };

  for (const line of lines) {
    if (isHeading(line)) {
      if (currentContent.length > 0) {
        sections[currentHeader] = (sections[currentHeader] || '') + '\n' + currentContent.join('\n');
        currentContent = [];
      }
      currentHeader = normalizeHeader(line);
    } else {
      currentContent.push(line);
    }
  }

  if (currentContent.length > 0) {
    sections[currentHeader] = (sections[currentHeader] || '') + '\n' + currentContent.join('\n');
  }

  return sections;
}

function findSectionByKeywords(sections, keywords) {
  for (const [header, content] of Object.entries(sections)) {
    for (const kw of keywords) {
      if (header.includes(kw.toUpperCase())) {
        return content.trim();
      }
    }
  }
  return '';
}

export function parseMistakeQuestions(rawText) {
  if (!rawText) return [];

  const questionSplits = rawText.split(/(?=(?:^|\n)\s*(?:\*\*)?Question(?:\s+\d+)?:?\s*(?:\*\*)?)/i);
  const parsed = [];

  for (const chunk of questionSplits) {
    const trimmed = chunk.trim();
    if (!trimmed || !/(?:^|\n)\s*(?:\*\*)?Question/i.test(trimmed)) continue;

    const extractField = (fieldName) => {
      const regex = new RegExp(`(?:^|\\n)\\s*\\*{0,2}${fieldName}:?\\*{0,2}\\s*([\\s\\S]*?)(?=(?:\\n\\s*\\*{0,2}(?:Question|Concept Tested|Why This Was Wrong|Why It Was Wrong|Correct Understanding|Correct Answer|Exam Strategy|Priority):?\\*{0,2})|$)`, 'i');
      const match = trimmed.match(regex);
      return match ? match[1].trim() : '';
    };

    const question = extractField('Question');
    if (!question || question.length < 5) continue;

    const conceptTested = extractField('Concept Tested');
    const whyWrong = extractField('Why This Was Wrong') || extractField('Why It Was Wrong') || extractField('Misunderstanding');
    const correctUnderstanding = extractField('Correct Understanding') || extractField('Key Concept');
    const correctAnswer = extractField('Correct Answer');
    const examStrategy = extractField('Exam Strategy') || extractField('Pro Tip') || extractField('Exam Tip');
    let priority = extractField('Priority') || 'High';

    if (/critical/i.test(priority)) priority = 'Critical';
    else if (/medium/i.test(priority)) priority = 'Medium';
    else if (/low/i.test(priority)) priority = 'Low';
    else priority = 'High';

    parsed.push({
      question: question.replace(/^[*\s]+/, ''),
      conceptTested: conceptTested.replace(/^[*\s]+/, ''),
      whyWrong: whyWrong.replace(/^[*\s]+/, ''),
      correctUnderstanding: correctUnderstanding.replace(/^[*\s]+/, ''),
      correctAnswer: correctAnswer.replace(/^[*\s]+/, ''),
      examStrategy: examStrategy.replace(/^[*\s]+/, ''),
      priority,
      rawChunk: trimmed
    });
  }

  return parsed;
}

export function parseDefinitions(rawText) {
  if (!rawText) return [];

  const items = [];
  const lines = rawText.split('\n');
  let currentItem = null;

  for (const line of lines) {
    const match = line.match(/^[\d.\-* ]*\*{2}([^*]+)\*{2}[:\-]?\s*(.*)$/);
    if (match) {
      if (currentItem) items.push(currentItem);
      currentItem = {
        term: match[1].trim(),
        definition: match[2].trim()
      };
    } else if (currentItem && line.trim()) {
      currentItem.definition += ' ' + line.trim();
    }
  }

  if (currentItem) items.push(currentItem);
  return items;
}

export function parseChecklistItems(rawText) {
  if (!rawText) return [];

  const items = [];
  const lines = rawText.split('\n');

  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed) continue;

    const match = trimmed.match(/^(?:[☐☑✓\-\*]|\[\s*\]|\d+\.)\s+(.+)$/);
    if (match) {
      const text = match[1].replace(/^\*\*|\*\*$/g, '').trim();
      if (text.length > 3) {
        items.push({
          id: text.slice(0, 40).toLowerCase().replace(/[^a-z0-9]/g, '_'),
          title: text
        });
      }
    }
  }

  return items;
}

export function parseStudyPlan(markdown, fallbackScore = 0) {
  if (!markdown) {
    return {
      score: fallbackScore || 0,
      profileText: '',
      performanceAnalysisText: '',
      mistakesText: '',
      mistakeQuestions: [],
      weakConceptsText: '',
      studyNotesText: '',
      definitionsText: '',
      definitions: [],
      checklistText: '',
      checklistItems: [],
      quizText: '',
      scheduleText: '',
      motivationText: '',
      rawMarkdown: ''
    };
  }

  const score = extractScore(markdown) ?? fallbackScore ?? 0;
  const sections = extractSections(markdown);

  const profileText = findSectionByKeywords(sections, ['STUDENT LEARNING PROFILE', 'LEARNING PROFILE', 'PROFILE']);
  const performanceAnalysisText = findSectionByKeywords(sections, ['PERSONAL PERFORMANCE ANALYSIS', 'PERFORMANCE ANALYSIS', 'PERFORMANCE SUMMARY']);
  const mistakesText = findSectionByKeywords(sections, ['WRONG QUESTION ANALYSIS', 'REVIEW OF INCORRECT QUESTIONS', 'MISTAKES', 'INCORRECT QUESTIONS']);
  const weakConceptsText = findSectionByKeywords(sections, ['WEAK CONCEPT PRIORITY', 'CONCEPT PRIORITY', 'PRIORITY MAP', 'WEAK CONCEPTS']);
  const studyNotesText = findSectionByKeywords(sections, ['PERSONALIZED STUDY NOTES', 'ADVANCED STUDY NOTES', 'STUDY NOTES']);
  const definitionsText = findSectionByKeywords(sections, ['KEY DEFINITIONS', 'DEFINITIONS', 'GLOSSARY']);
  const checklistText = findSectionByKeywords(sections, ['REVISION CHECKLIST', 'CHECKLIST', 'PERSONAL REVISION']);
  const quizText = findSectionByKeywords(sections, ['PRACTICE QUIZ', 'PRACTICE QUESTIONS', 'INTERACTIVE QUIZ']);
  const scheduleText = findSectionByKeywords(sections, ['STUDY SCHEDULE', 'ACTIONABLE STUDY SCHEDULE', 'ADAPTIVE STUDY SCHEDULE', 'TIMELINE']);
  const motivationText = findSectionByKeywords(sections, ['FINAL MOTIVATION', 'MOTIVATION', 'ENCOURAGEMENT']);

  const mistakeQuestions = parseMistakeQuestions(mistakesText);
  const definitions = parseDefinitions(definitionsText);
  const checklistItems = parseChecklistItems(checklistText || weakConceptsText);

  return {
    score,
    profileText: profileText || sections['intro'] || '',
    performanceAnalysisText,
    mistakesText,
    mistakeQuestions,
    weakConceptsText,
    studyNotesText,
    definitionsText,
    definitions,
    checklistText,
    checklistItems,
    quizText,
    scheduleText,
    motivationText,
    rawMarkdown: markdown
  };
}
